export const types = {
  CARGA__DATA: "[CHECKLIST] CARGA__DATA",
  EDITA__VALOR: "[CHECKLIST] EDITA__VALOR",
  FILTRAR__DATA: "[CHECKLIST] FILTRAR__DATA",
  FILTRAR__DATA__ALL: "[CHECKLIST] FILTRAR__DATA__ALL",
  SELECT__ITEM__DATA: "[CHECKLIST] SELECT__ITEM__DATA",
};

export const typesModal = {
  OPEN__MODAL: "[MODAL] OPEN__MODAL",
  CLOSE__MODAL: "[MODAL] CLOSE__MODAL",
};
